apiVersion: batch/v1
kind: Job
metadata:
  name: new-job
  namespace: q2
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        id: awesome-job
    spec:
      containers:
      - name: new-job-container
        image: busybox:1.31.0
        command: ["/bin/sh", "-c"]
        args: ["sleep 2 && echo done"]
      restartPolicy: Never
